CREATE TABLE IF NOT EXISTS Ator (
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Nome VARCHAR(35) NOT NULL,
    DataNasc DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Diretor (
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Nome VARCHAR(35) NOT NULL,
    DataNasc DATE NOT NULL,
    Biografia VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS Filme (
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Titulo VARCHAR(50) NOT NULL,
    AnoLancamento INT UNSIGNED NOT NULL,
    Sinopse VARCHAR(130) NOT NULL,
    NotaIMDB DECIMAL NOT NULL,
    DiretorId INTEGER NOT NULL,
    FOREIGN KEY (DiretorId) REFERENCES Diretor (Id)
);

CREATE TABLE IF NOT EXISTS Genero (
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Nome VARCHAR(25) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS FilmeAtor (
    FilmeId INTEGER NOT NULL,
    AtorId INTEGER NOT NULL,
    Papel VARCHAR(50),
    PRIMARY KEY (FilmeId, AtorId),
    FOREIGN KEY (FilmeId) REFERENCES Filme (Id) ON DELETE CASCADE,
    FOREIGN KEY (AtorId) REFERENCES Ator (Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FilmeGenero (
    FilmeId INTEGER NOT NULL,
    GeneroId INTEGER NOT NULL,
    PRIMARY KEY (FilmeId, GeneroId),
    FOREIGN KEY (FilmeId) REFERENCES Filme (Id) ON DELETE CASCADE,
    FOREIGN KEY (GeneroId) REFERENCES Genero (Id) ON DELETE CASCADE
);